version: '3'
services:
  nodered:
    container_name: trackers_nodered
    restart: always
    image: nodered/node-red:latest
    user: '0'    
    ports:
      - '45678:1880'
    volumes:
      - ./nodered:/data
      - ./files:/files
    links:
      - influx
  influx:
    container_name: trackers_influx
    restart: always
    image: influxdb
    user: '0'
    volumes:
      - ./influx:/var/lib/influxdb
    ports:
      - '45679:8086'
