version: '3'
services:
  nodered:
    container_name: trackers_nodered
    restart: always
    image: nodered/node-red
    user: '0'    
    ports:
      - '9000:1880'
    volumes:
      - ./nodered:/data
      - ./files:/files
    links:
      - mongo
      - broker
      - influx
  mongo:
    container_name: trackers_mongo
    restart: always
    environment:
      - MONGODB_AUTH=false
#      - MONGO_INITDB_ROOT_USERNAME=admin
#      - MONGO_INITDB_ROOT_PASSWORD=password
    image: mongo:latest
    user: '0'
    volumes:
      - ./mongo:/data/db
    ports:
#      - '27017:27017'
  mongo-express:
    container_name: trackers_mongo_express
    image: mongo-express
    restart: always
    ports:
      - 9081:8081
    environment:
#      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
#      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
  broker:
    container_name: trackers_broker
    restart: always
    image: eclipse-mosquitto
    user: '0'    
    ports:
      - '1883:1883'
      - '1884:1884'
#      - '8883:8883'
    volumes:
      - ./mosquitto:/mosquitto
#      - ./files:/files    
  influx:
    container_name: trackers_influx
    restart: always
    image: influxdb
    user: '0'
    volumes:
      - ./influx:/var/lib/influxdb
    ports:
#      - '8086:8086'
